### PR TITLE
accept the options from repl.start

### PR DESCRIPTION
**Pull request by dominictarr**
Still uses your defaults, and passes the tests.

Added a note in the README too,

cheers, Dominic.

### CODE REVIEW

**Comment by martinj** [comment]
Nice,
It looks like you converted from tabs to spaces in the code and the REAMDE doesn't look correctly formatted anymore. Please fix that before i merge.

Cheers!

**Comment by dominictarr** [comment]
Ah, sorry.

I'll fix that, also I've got some more additions.
added a `connect` method, because I usually want to make my own command and use a default port for my app.

Also, added the ability to pass in the contex and it just works like you expect.

**Comment by dominictarr** [comment]
okay I think I have it fixed now.
I've also added support of a context object.
so to create a repl you just go

``` js
repl.createServer(opts, {hello: function () {return 'HI'}}).listen(PORT)
```

and then 

``` js
repl.connect(PORT)
```

and then

```
> hello()
HI
```

**Comment by martinj** [comment]
Nice job!

**Pull request merged**
